### PR TITLE
MP#11 Tracking History API(Last five): CURD

### PR DESCRIPTION
**Pull request by jenniferhou762**
**DB schema**
```
CREATE TABLE histories (
        id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
         userid INT NOT NULL,
         item VARCHAR(255) NOT NULL,
         created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
         company VARCHAR(255) NOT NULL
);
```

**POST**
url: /histories.php
body: {"item":"xxxxxx"}
response:
no session: redirected to login.
success: status 200 with an empty body.
error: status 200 with a db error.

**GET**
url:/histories.php
response:
no session: redirected to login.
success: {"histories":["qqq","ppp"]}
error: status 200 with a db error.

### CODE REVIEW

**Comment by KunSu** [comment]
An HTML page that displays the current user's full history for each company is missing. 
An HTML page that displays the current user's last five histories for overall market place.
You can combine both HTML on the same page.

**Comment by jenniferhou762** [comment]
@KunSu  updated.

**Review by KunSu — CHANGES_REQUESTED** [review]
First of all, please do rebase the current master.
Secondly, where are the display pages?
I need an HTML page that simply **displays** a full list of users visited history.  
And I need another HTML page that simply **displays** the last five users visited history within each company.

**Comment by jenniferhou762** [comment]
@KunSu  Updated.

**Review by KunSu — APPROVED** [review]

**Pull request merged**
